ENV['SWIFT_VERSION'] = '5'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'DevFest Nantes' do
  use_frameworks!
  platform :ios, '15'
  pod 'KMPNativeCoroutinesCombine'
  pod 'KMPNativeCoroutinesAsync'
  pod "NSLogger/Swift"
  pod "URLImage"
  pod 'SwiftGen', '~> 6.6'
  # Firebase
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
end

target 'DevFest NantesTests' do
    inherit! :search_paths

end
